---
title: "Introduction"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    number_sections: true
    code_folding: hide
---

# Abstract

Die mathematisch fundierte Analyse von Kompositionsdaten geht zurück auf die Arbeit von J. Aitchison (1982). Seitdem wurden die Grundlagen u.a. durch Pawlowsky und Egozcue (..) 
kontinuierlich weiter entwickelt. Dank der Entdeckung eines metrischen Raumes für Kompositionsdaten, können die Daten mit fortgeschrittenen statistischen Methoden 
analysiert werden. In dieser Arbeit wird neben der grundsätzlichen Einführung in das Feld der Analyse von Kompositionsdaten, die Anwendung eines Monte-Carlo Expectation-Maximization 
Algorithmus (Steyer and Greven, 2023) für Kompositionsdaten umgesetzt. Die Wirksamkeit des Algorithmus wird anhand von Simulationsdaten evaluiert und anhand eines realen Beispiels 
aus dem Bereich der Geowissenschaften angewandt.

# Motivation

Das Feld der Kompositionsdaten erstreckt sich über eine Vielzahl an Fachbereichen. Sie sind überall dort relevant, wo es um die Analyse von relativen Anteilen eines Ganzen geht. Dazu 
gehören unter anderem auch die geowissenschaftliche Analyse von Sedimentdaten. Warum ist es in diesem Fall relevant und notwendig von Kompositionsdaten zu sprechen?
Der Grund hierfür liegt darin, dass die intuitive Anwendung von standardmäßig etablierten Methoden der multivariaten Datenanalyse auf Kompositionsdaten zu Fehlinterpretationen und Paradoxien
führen kann. Dafür sollen zwei kurze Beispiele angeführt werden, um die Problematik praktisch zu verdeutlichen (Vgl. Pawloswki et al., 2015, p. 1ff):

The field of compositional data spans across a variety of scientific disciplines. It becomes relevant wherever the analysis of relative proportions of a whole is concerned. This includes, 
among other areas, the geoscientific analysis of sediment data. Why is it relevant and necessary to specifically address these data as compositional?

The reason lies in the fact that the standard application of traditionally established methods of multivariate data analysis to compositional data can lead to misinterpretations and paradoxes. 
To practically illustrate these methodological challenges, two brief examples will be presented (cf. Pawlowsky et al., 2015, p. 1ff):

**Example 1: The scale of proportions**

Relative Daten verhalten sich anders als absolute Daten. Dies wird besonders deutlich, wenn prozentuale Veränderungen betrachtet werden. Stellen Sie sich vor Sie untersuchen zwei 
marine Sedimentschichten, um Rückschlüsse auf die Prozesse Staubeintrag und marine Produktivität zu ziehen. Für den Staubeintrag wird **Illit** als Proxy genommen und für die 
Produktivität Mineral **Kalzit**. Aufgrund der natürlichen Beschaffenheit des Sediments hat Illit einen Anteil von 0.1 % am Sediment und Kalzit einen Anteil von 20% in der 
ersten untersuchten Sedimentschicht. Beim Vergleich mit der zweiten Schicht wird festgestellt, dass der Anteil beider Mineralien sich um 0.1% erhöht hat, der Anteil von Illit ist 
0.2% und der von Kalzit ist 20.1%. Der Anstieg der relativen Veränderung ist also für beide Prozesse gleich. Genausogut ließe sich aber auch sagen, dass sich der Prozess des Staubeintrages
um 100% verstärkt hat und der Prozess der marinen Produktivität lediglich um 5%. In diesem Fall erscheint die Veränderung für den Staubeintrag deutlich relevanter zu sein als für die 
marine Produktivität. Beide Aussagen erscheinen zunächst einmal widersprüchlich und verdeutlichen, dass in einer sauberen Analyse die relative Bedeutung von Veränderungen erfasst werden 
muss. 

Relative data behave fundamentally different from absolute data. This becomes particularly evident when examining relative changes in percentages. Consider a scenario where two marine sediment 
layers are analyzed to draw conclusions about dust input and marine productivity processes. Illite serves as a proxy for dust input, while the mineral calcite indicates marine productivity. 
Due to the natural composition of the sediment, illite constitutes 0.1\% of the sediment, while calcite makes up 20\% in the first examined sediment layer. Comparison with the second layer 
reveals that both minerals increased by 0.1\%, resulting in 0.2\% for illite and 20.1\% for calcite. While the absolute increase of 0.1\% is identical for both processes, this same change can alternatively 
be interpreted on a relative dimension as a 100\% increase in dust input versus merely a 5\% increase in marine productivity. In this case, the change in dust input appears far more significant than the change in marine 
productivity. These seemingly contradictory interpretations highlight the necessity of capturing the relative significance of changes in a rigorous analysis.

**Example 2: spurious correlation**

Ähnlich verwirrende Konsequenzen kann das Auftreten von spurious correlation zeigen. Diese wurde bereits von Karl Pearson (1897) beschrieben und ist eine direkte Folge der Definition 
von Kompositionsdaten als Teil eines Ganzen. Wenn zum Beispiel eine Komposition aus drei Anteilen besteht und zwei davon positiv miteinander korrelieren, dann muss die dritte Komponente 
eine negative Korrelation aufweisen, auch wenn sie in Wirklichkeit unabhängig von den beiden anderen ist. Dies lässt sich auch am oben genannten Beispiel des Staubeintrages und der 
marinen Produktivität verdeutlichen. Beide Prozesse sind eindeutig voneinander unabhängig. Staub der von der Sahara ins Meer geweht wird hat eindeutig nichts mit mariner Produktivität zu tun.
Aber da beide Teile eines ganzen sind, kann es zu einem spurious correlation kommen, wenn der Staubeintrag so dominant wird, dass er den Prozess der marinen Produktivität verdrängt. 
In diesem Fall würde man eine nicht vorhandene negative Korrelation zwischen beiden Prozessen messen. 

Die Herausforderung von Kompositionsdaten sind seit über 100 Jahren bekannt. In den 1980er Jahren wurde von Aitchison eine Methodology eingeführt, die in der Lage war die oben 
genannten Probleme, die Folge der Beschränkungen im Stichprobenraum von Kompositionsdaten sind - dem Simplex, zu lösen. Entscheidend war die Einführung von logratios zur Erfassung der relativen Bezüge der Kompositionsanteile untereinander. Tatsächlich ermöglicht die 
Anwendung von logration Transformationen die Benutzung einer unbeschränkten multivariaten Statistik für Kompositionsdaten. Dies ist möglich, da logration Transformationen eine eins-zu-eins 
Beziehung zwischen den ursprünglichen Kompositionsdaten und ihren Logratios implizieren. Als die beiden bedeutsamsten Transformationen stellten sich die additative log ratio Transformation 
und die zentrierte log ratio Transformation heraus. 
Auf der Arbeit von Aitchison aufbauend, entwickelten mehrere Wissenschaftler (Egozcue, Pawloswki, Mateu-Figuras) in den 2000er Jahren eine algebraisch-geometrische Struktur auf 
dem Grundraum von Kompositionsdaten. Mit diesem metrischen Vektorraum ist es möglich komplexere multivariate Methoden umzusetzen. Ein Beispiel dafür ist die Umsetzung von Maximum 
Likelihood Verfahren zur Berechnung von latenten Parametern. Als Anwendungsbeispiel soll in dieser Arbeit die Methode von Steyer und Greven (2023) für die Durchführung einer Principal Component 
Analyse mit Dichten mit Hilfe eines Monte-Carlo Expectation-Maximisation (MCEM) Algorithmus auf den Fall von Zähl Kompositionen angewendet werden.
Dafür ist es zunächst einmal notwendig die Struktur des Grundraumes von Kompositionsdaten zu definieren. Darauf aufbauend wird die Übertragung des MCEM Algorithmus von Steyer und Greven 
als ein Beispiel für die Anwendungsmöglichkeiten komplexer multivariater Methoden umgesetzt. Die Umsetzung wird einmal am Beispiel von simulierten Daten evaluiert und mit Hilfe eines 
realen geowissenschaftlichen Datensatzes angewandt, um die Mächtigkeit des Ansatzes zu demonstrieren.    

"add statistical rigor to the existing empirical analysis..."

Similarly confounding consequences can arise from spurious correlation. A phenomenon first described by Karl Pearson in 1897 as a direct consequence of the definition of compositional data as 
consisting of parts of a whole. 
For instance, in a three-part composition, if two components show positive correlation, the third component must exhibit negative correlation, even if it is inherently independent of the others. 
This can be illustrated using the previous example of dust input and marine productivity. These processes can be assumed to be independent - Saharan dust blown into the sea has no inherent connection to 
marine productivity. However, since both are parts of a whole, spurious correlation can emerge when dust input becomes so dominant that it replaces marine productivity in the sediment, resulting in the 
measurement of a non-existent negative correlation between these processes.

The challenges of compositional data have been recognized for over a century. First warnings that standard multivariate techniques lead to missleading results were issued in the fields of geology and biology 
in the 60s. In the 1980s, John Aitchison introduced a methodology capable of addressing the problems arising from the 
constraints in the sample space of compositional data - the simplex. The key innovation was the introduction of log-ratios to capture the relative relationships between compositional parts and preserving scale invariance. 
Indeed, log-ratio transformations enable the application of multivariate statistics to compositional data, as they identify a one-to-one relationship between the sample space of compositional data 
and the real space. The additive log-ratio and centered log-ratio transformations emerged as the most significant transformations at that time.

Building on Aitchison's work, several scientists (Egozcue, Pawlowski, Mateu-Figueras) developed an algebraic-geometric structure for the sample space of compositional data in the early 2000s. 
The recognition of an Euclidean vector space on the simplex and the development of the isometric log-ratio (ilr) transformation enabled the implementation of more complex multivariate methods.
One of the advantages of this approach was ability to define random compositions on the simplex, which allowed the utilization of advanced statistical tools, like maximum likelihood estimation methods 
 for calculating parameters of latent models. As a practical application, 
this work will adapt the method of Steyer and Greven (2023) for conducting Principal Component Analysis with sparsely observed densities using a Monte-Carlo Expectation-Maximization (MCEM) algorithm to 
an application with count compositions.

To achieve this, it is first necessary to define the structure of the fundamental space of compositional data. Building on this foundation, the adaptation of Steyer and Greven's MCEM algorithm 
will be implemented as an example of applying complex multivariate methods. The implementation will be evaluated using simulated data and applied to a real geoscientific dataset to demonstrate 
the power of this approach.

# Basic principles of Compositional Data analysis

Dieses Kapitel führt in die auf Aitchison aufbauende Definition von Kompositionsdaten und ihre wichtigsten Merkmale bzw. Grundprinzipien ein. Darauf aufbauend wird der Vektorraum für 
Kompositionsdaten, die sogenannte Aitchison Geometry, und seine Basisoperationen definiert. Um die Grundlage für die multivariate Datenanalyse zu schaffen, werden die beiden grundlegenden 
Transformationsverfahren, die isometrische logratio Transformation und die zentrierte logratio Transformation erläutert und ihr Bezug zueinander herausgearbeitet. Diese Transformationen 
ermöglichen die Analyse in einem reelen Euklidischen Raum, die für die spätere Umsetzung multivariater Methoden notwendig ist. Im Hinblick auf die Arbeit mit dem praktischen geowissenschaftlichen 
Datensatz, werden außerdem die wichtigsten deskriptiven Methoden zur Darstellung von Kompositionsdaten vorgestellt. 

This chapter introduces the definition of compositional data based on the work of Aitchison (1984) and presents its fundamental principles. Following this fundament concepts, the vector 
space for compositional data, known as the Aitchison Geometry, with its basic operations and metric structure are defined.  
To etablish the framework for multivariate data analysis two fundamental transformation methods for compositional data and the relation between them are introduced: the centered log-ratio 
transformation (clr) and the isometruc log-ratio transformation (ilr). These transformations enable analysis in real Euclidean space, which is essential for the subsequent implementation 
of standard multivariate methods. In addition, the most important descriptive methods for representing compositional data are presented with regard to working with the marine sediment dataset.   

## Introduction

Wie bereits erwähnt definieren sich Kompositionsdaten dadurch, dass sie sich aus Teilen eines Ganzen zusammensetzen. Daraus folgt ihre Beschreibung als multivariater Datensatz mit 
dessen Anteile relative anstatt absoluter Informationen enthalten, dessen Teile strikt positive sind und die sich zu einer Konstanten aufsummieren. In der Praxis trifft dies auf eine 
Viezahl an Datensätzen zu, z.B. die Stimmenanteile von Parteien bei Wahlen, Anteile von bestimmten Beschäftigungsverhältnissen auf dem Arbeitsmarkt, Organismen in einem Ökosystem oder 
die Anteile chemischer Mineralien in Sedimenten. 
Die grundlegende Charakteristik von Kompositionsdaten als Zusammensetzung von relativen Anteilen eines Ganzen lässt sich wie folgt definieren (Pawloswky-Glahn et al. 2015, p. 8)

**Definition 1: D-part composition**
A (row) vector $\boldsymbol{x} = (x_1, x_2, ..., x_D)$ is a D-part composition when all its compositional parts are strictly positive and carry only relative information.

The defining characteristic of compositional data is that is consists of compositional parts that represent parts of a whole. This leads to their identification as a 
multivariate datset whose compositional parts contain relative rather than absolute information. Furthermore, due to the nature of compositional parts, they are strictly 
positive and sum to a constant. In practice, this applies to a rich variaty of datasets, such as party vore shares in elections, proportions of different employment sectors 
in the labor market, organisms in an ecosystem, or the poportions of minerals in sediments.  
Following those fundamental characteristics, compositional data can be defined as follows: 

Der beobachtete Vektor $\boldsymbol{x}$ enthält in der Regel die beobachteten Werte für die $D$ Komponenten, die im Kontext dieser Arbeit Kompositionsteile genannt werden. Die Summe der 
beobachteten Werte wird als Ganzes oder Total bezeichnet. Dabei ist die Größe des Ganzen für die Definition als Kompositionsdaten nicht relevant und es ist auch nicht notwendig, dass diese 
über mehrere Beobachtungen aus einer Grundgesamtheit konstant ist, wie dies bei einigen älteren und exklusiveren Definitionen der Fall ist. Dies kann dadurch verdeutlicht werden, dass die 
Multiplikation des eingeführten Vektors $\boldsymbol{x}$ mit einem positiven Skalar $c > 0$ keine Auswirkungen auf die relativen Anteile der Komponenten hat. Aufgrund dieser Übereinstimmung 
der relativen Informationen, können die in Definition 1 definierten Vektoren als Teil einer Equivalenzklasse von Kompositionsvektoren beschrieben werden, deren Ganzes voneinader abweicht, 
aber deren relative Information identisch ist (Vgl. Pawlowsky-Glahn et al 2015,p.9).  

The vector $\boldsymbol{x}$ typically contains the observed values for the $D$ components, which, for terminological precision, are called compositional parts in the context of this thesis. 
The sum of these of the observed values or compositional parts is referred to as the whole or total. Notably, the magnitude of the whole the whole is not relevant for the definition of a 
composition, and it is not necessary for this total to remain constant across multiple observations from a population of compositions, as was required in some older and more restrictive definitions. 
This can be illustrated by the fact that multiplying the vector $\boldsymbol{x}$ by a positive scalar $c > 0$ has no effect on the proportions of the compositional parts. Due to this preservation 
of relative information, the defined D-part composition ~\ref{def:dpart} can be described (TODO: better expression? see literature) as members of an of an equivalence class of compositional vectors 
whose totals may differ but whose relative information remains idenftical 

In der Praxis ist es üblich beobachteten Kompositionen eine konstante Summe zuzuordnen, um sie als Teil eines festen Ganzen zu betrachten, z.B. als prozentuale Anteile mit einer konstanten Summe 
von eins oder als ppm (parts per Million). Derartige Vektoren werden in der Literatur auch als *closed data* bezeichnet und die Operation einer Komposition eine konstante Summe zuzuordnen 
als *closure*: 

In practice, it is common to assign a constant sum to observed compositions to make them comparable. Typical examples are relative shares with a constant sum of one or ppm (parts per million). 
Such vectors are referred to in the literature as *closed data*. and the operation of assigning a constant sum to a composition $\boldsymbol{x}$ is called a *closure*:

**Definition 2: closure**
For any compositional vector $\boldsymbol{x} = (x_1, x_2, ..., x_D)$ with positive components, the closure of $\boldsymbol{x}$ to a constant $\kappa > 0$ is defined as
$$
\mathcal{C}(\mathbf{x})=\left[\frac{\kappa \cdot x_{1}}{\sum_{j=1}^{D} x_{j}}, \frac{\kappa \cdot x_{2}}{\sum_{j=1}^{D} x_{j}}, \ldots, \frac{\kappa \cdot x_{D}}{\sum_{j=1}^{D} x_{j}}\right]
$$

Again, it is important to emphasize that the closure operator implies that every observed composition can be *rescaled* such that the sum over its components equals $\kappa$ without any loss of 
relative information between the compositional parts. This property leads to the following definition of equivalence classes for compositional vectors:

**Definition 2b: equivalence class**
Two vectors of $D$ positive real components $\mathbf{x}, \mathbf{y} \in \mathbb{R}_{+}^{D} \quad \left(x_{j}, y_{j}>0\right.$, for all $j=1,2, \ldots, D)$ are compositionally equivalent if 
\mathcal{C}(\mathbf{x}) = \mathcal{C}(\mathbf{y}).

[TODO: is change between x and pi necessary?] -> hier Einführung \pi sinnvoll -> latent composition has a closure with \kappa = 1

In der Regel können beobachtete Kompositionen als zufällige Ziehungen aus einer latenten Komposition $\boldsymbol{\pi} = (\pi_1, \pi_2, ..., \pi_D)$ modelliert werden, welche die zugrunde 
liegenden Anteile der Komposition enthält.  
In diesem Sinne sind die beobachten Häufigkeiten der einzelnen Kompositionsteile Ziehungen aus der zugrunde liegenden Komposition $\boldsymbol{\pi}$. Im Kapitel [...] werden wir die beobachteten 
Kompositionsdaten als als count composititions definieren, die einer multinomalialen Zufallsverteilung folgen. Zur Einführung von Kompositionsdaten im Allgemeinen ist es jedoch lediglich 
notwendig darauf zu verweisen, dass im Folgenden für beobachtete Kompositionen eine Notation mit fettgedruckten, kleingeschriebenen Buchstaben (z.B. $\boldsymbol{x}) und für latente Kompositionen 
$\boldsymbol{\pi}$ verwendet wird.
Die zugrunde liegende latente Komposition kann auch als Dichte einer diskreten Verteilung mit $D$ Ausprägungen angesehen werden, es gilt also $\sum_{i=1}^D \pi_i = 1$. An dieser Stelle 
ist es offensichtlich, dass latente Kompositionen ein Beispiel für Kompositionsdaten mit einer konstanten Summe von eins sind.

Anhand dieses Beispiels aus dem Feld der Zufallsvariablen wird deutlich, dass beobachtete Kompositionen sich zwar auf den ersten Blick stark unterscheiden können, z.B. weil sie in unterschiedlichen 
Häufigkeiten oder Einheiten gemessen wurden. Trotzdem können sie dieselben relativen Informationen enthalten.In diesem Sinne sind beobachtete Kompositionsdaten Representationen einer Komposition, 
dass heißt einer Equivalenzklasse. [TODO: Definition einfügen?]

Auf dieser Argumentation aufbauend, kann der Grundraum für Kompositionsdaten definiert werden:

Mit Hilfe dieser Vorüberlegungen kann der Grundraum aller möglichen Kompositionen definiert werden. Dieser wird der Tradition Atchisons folgend als Simplex bezeichnet:

**Definition 3: sample space**
The sample space of compositional data is the simplex,
$\mathcal{S}^{D}=\left\{\boldsymbol{x} \in \mathbb{R}^{D} \mid \sum_{j=1}^{D} x_{j}=\kappa, x_{j} \geq 0 \forall j=1, \ldots, D\right\}$.

Nachdem in der Einführung die Grundelemente in der Arbeit mit Kompositionsdaten vorgestellt wurden, wird im nächsten Schritt dagelegt, auf welchen Grundprinzipien eine statistisch 
valide Arbeit mit Kompositionsdaten zu erfolgen hat. Dies ist notwendig, da die Anwendung von Standardmethoden der statistischen Analyse zu einer Reihe von Problemen führt.
Neben den bereits erwähnten Besonderheiten oder Paradoxien bei der Arbeit mit Kompositionsdaten, gibt es auch eine Reihe von handfesten Problemen bei der Anwendung von multivariaten 
Methooden (Boogart et al. 2013, p. 2):
- Indepentent compositional parts can show spurious correlation
- The covariance of two compositional parts depends on the other compositional parts included in the analysis
- Variance matrixes of compositional data are singular
- The values of compositional data can not follow a normal distribution due to its bounded range.

Um diese Probleme zu vermeiden, wurden von WissenschaftlerInnen wie Aitchison (1982) und Pawlowsky-Glahn (2015) Grundsätze entwickelt, die eine mathematisch fundierte Arbeit mit relativen 
Daten ermöglichen. Diese Grundsätze und die von Aitchison entwickelten Operationen eines Euklidischen Vektorraumes auf dem Simplex werden im Folgenden vorgestellt.

Having introduced the fundamental elements of compositional data analysis, now the the core principles required for statistically valid work with compositional data will be established. 
This is essential because applying standard statistical tools leads to several significant problems. 
Beyond the already mentioned paradoxes that apply when working with compositional data, there are also a number of specific problems when conducting standard multivariate analysis (Boogart et al. 2013, p. 2):

- Independent compositional parts can show spurious correlation
- The covariance of two compositional parts depends on the other compositional parts included in the analysis
- Variance matrices of compositional data are singular
- The values of compositional data cannot follow a normal distribution on the simplex due to their bounded range

To address these challanges, researchers such as Aitchison (1982), Egozcue (2005) and Pawlowsky-Glahn (2015) developed principles that enable mathematically rigorous analysis of relative data. The 
principles and the operations of an Euclidean vector space on the simples developed by Aitchison (1982) are presented in the following section.

## Principles of CoDa

Die Daten auf dem Simplex müssen folgenden drei Prinzipien gerecht werden, um eine robuste und widerspruchsfreie statistische Analyse zu ermöglichen (Aitchison ??, Pawlowsky-Glahn et al. 2015, p. 12):

1. Scale invariance:
Das Prinzip der Scale invariance lässt sich aus der Definition der Equivalenzklasse von Kompositionen ableiten. Es bedeutet, dass die relavtiven Informationen in den Kompositionsteilen unabhängig von 
der Einheit sind, in der diese erfasst werden, solange alle in derselben Einheit gemessen werden. In diesem Sinne muss jede Komposition invariant gegenüber jeder Veränderung der Skalierung 
sein. Mathematisch kann dies für eine beliebige Funktion $f( )$ in $\mathbb{R}^{D}$ wie folgt definiert werden (Pawloswky-Glahn et al. 2015, p.14): The function $f$ is scale invariant if it 
satisfies $f(\lambda \boldsymbol{\pi}) = f(\boldsymbol{\pi})$ for all $\lambda > 0$ and any compistion $\boldsymbol{\pi} \in \mathcal{S}^{D}$.

2. Permutation invariance:
It is required that any change in the order of compositional parts does not influence the analyses, i.e. any function $f$ is permutation invariant if it results in equivalent results when 
the order of the compositional parts is changed.

A typical choice for $f$ that follows both of the principles mentioned so far are log ratios for the compositional parts. It is obvious that ratios are scale invariant since $f(\boldsymbol{\pi}) = \pi_1 / \pi_2 = (\lambda * \pi_1) / (\lambda * \pi_2)$.
But ratios depend on the order of the compositional parts. Therefore, the logratio is choosen $f(\boldsymbol{\pi}) = \log(\pi_1 / \pi_2)$. Since $\log(\pi_1 / \pi_2) = - \log(\pi_2 / \pi_1)$ 
it is clear that a change in the order only results in a change of sign and the logratio provides a symmetry with respect to the ordering of parts.

3. Subcompositional coherence:
A subcompisition is a subset of a composition. The last principle of subcompositional coherence states that any the choice a subcomposition does not affect the statistical properties of the 
composition. This principle can be illustrated in two dimensions. The first is that of *subcompositional dominance* and states that the distance between two full compositions must be greater 
or equal to the distance between any two subcomposition. Again, it is useful to mention that the standard Euclidean distance does not fullfill this principle when applied to compositional data.
The second dimension of this principle is that of *ratio preserving*, which means that the choice of a subcomposition does not affect the ratio between the remaining parts.

Data on the simplex must satisfy the following three principles to enable a robust and consistent statistical analysis citet{Aitchison2018, Pawlowsky-Glahna}:

\begin{enumerate}
    \item Scale invariance
    
    The principle of scale invariance is closely related to the definition of the equivalence classes of compositions. It means that the relative information in the compositional parts is 
    independent of the unit in which they are measured, as long as all parts are measured in the same unit. As a consequence, every composition must be invariant to any change in 
    scaling. Mathematically, this can be defined for any function $f( )$ in $\mathbb{R}^{D}$ as follows citep[p.~14]{PawlowskyGlahna}: The function $f$ is scale invariant if it 
    satisfies $f(\lambda \boldsymbol{x}) = f(\boldsymbol{x})$ for all $\lambda > 0$ and any composition $\boldsymbol{x} \in \mathcal{S}^{D}$.

    \item Permutation invariance
    
    It is required that any change in the order of compositional parts does not influence the analyses, i.e. any function $f$ is permutation invariant if it results in equivalent results 
    when the order of the compositional parts is changed. \\

    A typical choice for $f$ that follows the first principle of scale invariance are ratios for the compositional parts. It is obvious that ratios are scale invariant since $f(\boldsymbol{x}) = x_1 / x_2 = (\lambda * x_1) / (\lambda * x_2)$. 
    But ratios depend on the order of the compositional parts, therefore violating the second principle. Therefore, the logratio is chosen $f(\boldsymbol{x}) = \log(x_1 / x_2)$. Since 
    $\log(x_1 / x_2) = - \log(x_2 / x_1)$ it becomes clear that a change in the order only results in a change of sign and the log-ratio provides a symmetry with respect to the ordering of parts.

    \item Subcompositional coherence

    A subcomposition is a subset of a composition. The third principle of subcompositional coherence states that the choice of a subcomposition does not affect the statistical properties of the 
    composition. This principle can be illustrated in two dimensions. The first dimension is called \emph{subcompositional dominance} and states that the distance between two complete compositions must 
    be greater or equal to the distance between any two subcompositions. Again, it is useful to mention that the standard Euclidean distance does not fullfill this principle when applied to 
    compositional data. \autoref{subsec:operations} is going to introduce the Aitchison distance that follows the principle of \emph{subcompositional dominance}. 
    The second dimension of subcompositional coherence is called \emph{ratio preseving}, which means the choice of a subcomposition does not affect the ratio between the remaining parts.

\end{enumerate}


## Operations of the vector space

Als erstes müssen wir feststellen, dass der im Umgang mit absoluten Werten gewohnte Euklidische Raum als linearer Vektorraum mit seiner metrischen Struktur nicht geeignet ist für Kompositionsdaten. 
Mathematische Operationen auf dem Simplex erscheinen auf den ersten Blick nicht so einfach, wie im gewohnten reelen Raum. Aber auch auf dem Simplex ist es möglich einen Euklidischen Vektorraum 
zu definieren. Dafür benötigen wir zwei Operationen, die Addition und Multiplikation im reelen Raum entsprechen und die angepassten Definitionen vom Skalarprodukt der Norm und der Distanz.

First, it is important to recognize that the standard Euclidean space commonly used for absolute values, with its linear vector space structure and metric properties, is not suitable for analyzing compositional data. 
At first glance, mathematical operations on the simplex appear quite different from the familar operations in real space. However, it is possible to define a Euclidean vector space on the simplex 
as well. To accomplish this, two fundamental operations that correspond to addition and multiplication are needed.

**Definition 4: Perturbation**
For two compositional vectors $\boldsymbol{x}$ and $\boldsymbol{y}$ in $\mathcal{S}^{D}$ their perturbation is defined as:
$$
\mathbf{x} \oplus \mathbf{y}=\mathcal{C}\left[x_{1} y_{1}, x_{2} y_{2}, \ldots, x_{D} y_{D}\right] \in S^{D}
$$

**Definition 5: Powering**
The powering of a compositional vector $\boldsymbol{x}$ in $\mathcal{S}^{D}$ by a constant $a \in \mathbb{R}$ is defined as:
$$
\alpha \odot \mathbf{x}=\mathcal{C}\left[x_{1}^{\alpha}, x_{2}^{\alpha}, \ldots, x_{D}^{\alpha}\right] \in \mathcal{S}^{D}
$$

To complete the vector space structure, the so called the Aitchison geomtry, we need to define a scalar product with its associated norm and distance (Pawloswky-Glahn et al. 2015, p. 26):
**Definition 6: Aitchison inner product**
Inner product of $\mathbf{x}, \mathbf{y} \in S^{D}$,
$$
\langle\mathbf{x}, \mathbf{y}\rangle_{a}=\frac{1}{2 D} \sum_{i=1}^{D} \sum_{j=1}^{D} \ln \frac{x_{i}}{x_{j}} \ln \frac{y_{i}}{y_{j}}
$$
**Definition 7: Aitchison norm**
Norm of $\mathbf{x} \in \mathcal{S}^{D}$,
$$
\|\mathbf{x}\|_{a}=\sqrt{\frac{1}{2 D} \sum_{i=1}^{D} \sum_{j=1}^{D}\left(\ln \frac{x_{i}}{x_{j}}\right)^{2}}
$$
**Definition 8: Aitchison distance**
Distance between $\mathbf{x}$ and $\mathbf{y} \in S^{D}$,
$$
\mathrm{d}_{a}(\mathbf{x}, \mathbf{y})=\|\mathbf{x} \ominus \mathbf{y}\|_{a}=\sqrt{\frac{1}{2 D} \sum_{i=1}^{D} \sum_{j=1}^{D}\left(\ln \frac{x_{i}}{x_{j}}-\ln \frac{y_{i}}{y_{j}}\right)^{2}}
$$

The two operations on the simplex, perturbation and powering define an Euclidean linear vector space, that is usually called \emph{Aitchison geomtry on the simplex}, with its metrics the Aitchison 
inner product, norm and distance.
Those operations define a hilbert space on the simplex (TODO: definition of a vector space). For historical reasons it is called the Aitchison geometry. But in mathematical terms it 
is also a real Euclidean space or a finite dimensional real Hilbert space.
This allows now for the use of all statistical methods that are available for the standard Euclidean space. (TODO: umformulieren)

## Clr transformation (generating systems)

Wie bereits erwähnt, folgt diese Arbeit dem Prinzip der Arbeit in Koordinaten. Das heißt, dass wir zunächst einmal die Kompositionen aus Definition [...] in Koordinatenform 
darstellen müssen. Das Ziel ist es Kompositionen in einem orthogonalen Koordinatensystem darzustellen. Dafür sind eine Reihe von Schritten notwendig und im Folgenden werden zu 
diesem Zweck die bekannten Transformationen von Kompositionsdaten, die clr-Transformation und die ilr-Transformation, vorgestellt. Typischerweise wird in diesem Zusammenhang 
in der Regel noch die alr-Transformation vorgestellt, die historisch betrachtet als erstes entwickelt wurde. Im Kontext dieser Arbeit kann jedoch darauf verzichtet werden, weil 
sie keinen notwendigen Beitrag zur Arbeit in Koordinaten leistet.

As previously mentioned, this work is based on the \emph{principle of working on coordinates}, as outlined by \citet{Figueras2011}. This implies that we must first find a way to represent the compositions 
from Definition [...] within an orthogonal system. Achieving this requires a series of steps, and to this end, two well-known transformations for compositional data, the centered log-ratio (clr) 
transformation and the isometric log-ratio (ilr) transformation, will be introduced in the following. Typically, the additive log-ratio (alr) transformation is also presented in 
this context, as it was historically the first to be developed. However, in the context of this work, it can be omitted because it does not make a necessary contribution to the 
\emph{principle of working on coordinates}.

Im Allgemeinen sind wir es gewohnt Vektoren anhand ihrer kanonischen Basis $\left\{\mathbf{e}_{1}, \mathbf{e}_{2}, \ldots, \mathbf{e}_{D}\right\}$ in $\mathcal{R}^D$ zu beschreiben. 
Dies gilt auch für den Fall, dass der Vektor eine beobachtete Komposition $\boldsymbol{x}$ ist. In diesem Fall kann der Vektor $\boldsymbol{x}$ als Linearkombination der Basisvektoren
dargestellt werden: 
$$
\mathbf{x}=x_{1}[1,0, \ldots, 0]+x_{2}[0,1, \ldots, 0]+\ldots+x_{D}[0,0, \ldots, 1]=\sum_{j=1}^{D} x_{j} \cdot \mathbf{e}_{j} \tag{X}
$$
Das Problem ist, dass die Vektoren $\left\{\mathbf{e}_{1}, \mathbf{e}_{2}, \ldots, \mathbf{e}_{D}\right\}$ keine Basis in Bezug auf den Vektorraum des in [...] definierten Simplex sind. 
Zum einen liegen nicht alle Linearkombinationen von Koeffizienten $x_i$ im Simplex (negative und Nullwerte sind nicht erlaubt). Zum anderen liegen die Vektoren $\boldsymbol{e}_{j}$ nicht 
in $mathcal{S}^D$ (siehe Definition 1) (Cp. Pawloswky-Glahn et al. 2015, p. 33).

In general, we are accustomed to describing vectors using their canonical basis $\left\{\mathbf{e}_{1}, \mathbf{e}_{2}, \ldots, \mathbf{e}_{D}\right\}$ in $\mathcal{R}^D$. 
This also applies when the vector is an observed composition $\boldsymbol{x}$. In this case, the vector $\boldsymbol{x}$ can be represented as a linear combination of the basis vectors:
\begin{equation}
    \mathbf{x}=x_{1}[1,0, \ldots, 0]+x_{2}[0,1, \ldots, 0]+\ldots+x_{D}[0,0, \ldots, 1]=\sum_{j=1}^{D} x_{j} \cdot \mathbf{e}_{j} \tag{X}
\end{equation}
The problem with this representation is that the vectors $\left\{\mathbf{e}_{1}, \mathbf{e}_{2}, \ldots, \mathbf{e}_{D}\right\}$ do not form a basis with respect to the vector space of the 
simplex defined in Definition \autoref{def:simplex}. Firstly, not all combinations of coefficients $x_i$ result in an element of $S^{D}$ (negative and zero values are not allowed). Secondly, 
the basis vectors $\mathbf{e}_{j}$ do not lie in the simplex (cf. Definition \autoref{def:simplex}) \citep[p.~33]{PawlowskyGlahn2015a}.



Zum Verständnis von Kompositionen ist es aber überaus hilfreich die Kompositionsteile $\left\{x_{1}, x_{2}, \ldots, x_{D}\right\}$ als Koordinaten in Bezug auf eine Basis zu beschreiben, 
weswegen es durchaus sinnvoll ist, einen statistisch validen Weg zu finden dies auch zu tun.
Pawlowsky-Glahn et al. (2015) zeigen, dass die clr-Transformation ein wichtiger Schritt auf dem Weg zu einer solchen Basis ist. Zunächst einmal macht es für Kompositionsdaten Sinn ein 
generatives System zu identifizieren, indem die kanonische Basis exponentiert wird. Dies resultiert in $\left\{\mathbf{w}_{1}, \mathbf{w}_{2}, \ldots, \mathbf{w}_{D}\right\}$ mit 
$$
\mathbf{w}_{j}=\mathcal{C}\left(\exp \left(\mathbf{e}_{j}\right)\right)=\mathcal{C}[1,1, \ldots, e, \ldots, 1], \quad j=1,2, \ldots, D . \tag{X}
$$.
Dieses generative System kann genutzt werden, um den Kompositionsvektor als perturbation-linear Kombination seiner logarithmierten Kompositionsteile zu beschreiben (Cp. Pawlowsky-Glahn et al 2015, p. 34): 

$$
\mathbf{x} =\bigoplus_{j=1}^{D} \ln \frac{x_{j}}{\mathrm{~g}_{m}(\mathbf{x})} \odot \mathbf{w}_{j} 
=\ln \frac{x_{1}}{\mathrm{~g}_{m}(\mathbf{x})} \odot[e, 1, \ldots, 1] \oplus \ldots \oplus \ln \frac{x_{D}}{\mathrm{~g}_{m}(\mathbf{x})} \odot[1,1, \ldots, e], \tag{X}
$$ 

wobei 
$$
\mathrm{g}_{m}(\mathbf{x})=\left(\prod_{j=1}^{D} x_{j}\right)^{1 / D}=\exp \left(\frac{1}{D} \sum_{j=1}^{D} \ln x_{j}\right)
$$
den geometrischen Mittelwert der Komposition darstellt.

Nevertheless, for understanding compositions, it would be very helpful to describe the compositional parts $\left\{x_{1}, x_{2}, \ldots, x_{D}\right\}$ as coordinates with respect to a basis. 
Therefore, it is quite useful to find a statistically valid way to do this. \\
\citet{PawlowskyGlahn2015a} show that the clr-transformation is an important step towards such a basis. As will be shown below, it is possible to use the clr-transformation for multivariate 
data analysis as it is a valid one-to-one transformation from the simplex onto the real space. However, for the purpose of finding an orthonormal basis, the clr-transformation can be seen as an intermediate step. \\
First, it makes sense to identify a generating system by exponentiating the canonical basis. This results in $\left\{\mathbf{w}_{1}, \mathbf{w}_{2}, \ldots, \mathbf{w}_{D}\right\}$ with
\begin{equation}
    \mathbf{w}_{j}=\mathcal{C}\left(\exp \left(\mathbf{e}_{j}\right)\right)=\mathcal{C}[1,1, \ldots, e, \ldots, 1], \quad j=1,2, \ldots, D. \tag{X}
\end{equation}
This generating system can be used to describe the compositional vector as a perturbation-linear combination of its log-transformed compositional parts \citep[p.~34]{PawlowskyGlahn2015a}:
\begin{equation}
    \mathbf{x} =\bigoplus_{j=1}^{D} \ln \frac{x_{j}}{\mathrm{~g}_{m}(\mathbf{x})} \odot \mathbf{w}_{j} 
    =\ln \frac{x_{1}}{\mathrm{~g}_{m}(\mathbf{x})} \odot[e, 1, \ldots, 1] \oplus \ldots \oplus \ln \frac{x_{D}}{\mathrm{~g}_{m}(\mathbf{x})} \odot[1,1, \ldots, e], \tag{X}
\end{equation}
where
\begin{equation}
    \mathrm{g}_{m}(\mathbf{x})=\left(\prod_{j=1}^{D} x_{j}\right)^{1 / D}=\exp \left(\frac{1}{D} \sum_{j=1}^{D} \ln x_{j}\right)
\end{equation}
represents the geometric mean of the composition.

Es ist ersichtlich, dass dies ausgehend von den formulierten Grundprinzipien (Chapter [..]) und der Aitchison-Geometrie ein kompositionelles Equivalent zu der kanonischen Basis ist. Darüber hinaus 
entsprechen die Koefficienten in [.. ] den von Aitchison definierten Koefficienten der centered logratio Transformation (clr).  
**Definition: clr-Transformation**
$\boldsymbol{\rho}=\operatorname{clr}(\boldsymbol{\pi})=\left(\log \left(\pi_{1}\right)-\frac{1}{N} \sum_{k=1}^{N} \log \left(\pi_{k}\right), \ldots, \log \left(\pi_{N}\right)-\frac{1}{N} \sum_{k=1}^{N} \log \left(\pi_{k}\right)\right)$

Die clr Koordinaten haben eine Reihe von Vorteilen. Insbesondere 
gilt für eine Komposition $\boldsymbol{\boldsymbol{x}}_{j} \in \mathcal{S}^{D}$, dass durch die clr-Transformation eine eindeutige Beziehung zwischen den Operationen auf dem Simplex (chapter [...]) und dem 
reelen Raum hergestellt werden kann.  
Für realen konstanten $\alpha, \beta$ gilt für alle $j=1,2$:  
(a) $\operatorname{clr}\left(\alpha \odot \mathbf{x}_{1} \oplus \beta \odot \mathbf{x}_{2}\right)=\alpha \cdot \operatorname{clr}\left(\mathbf{x}_{1}\right)+\beta \cdot \operatorname{clr}\left(\mathbf{x}_{2}\right)$;  
(b) $\left\langle\mathbf{x}_{1}, \mathbf{x}_{2}\right\rangle_{a}=\left\langle\operatorname{clr}\left(\mathbf{x}_{1}\right), \operatorname{clr}\left(\mathbf{x}_{2}\right)\right\rangle ;$  
(c) $\left\|\mathbf{x}_{1}\right\|_{a}=\left\|\operatorname{clr}\left(\mathbf{x}_{1}\right)\right\|, \quad \mathrm{d}_{a}\left(\mathbf{x}_{1}, \mathbf{x}_{2}\right)=\mathrm{d}\left(\operatorname{clr}\left(\mathbf{x}_{1}\right), \operatorname{clr}\left(\mathbf{x}_{2}\right)\right)$.Die Eigenschaft (a) sagt uns, dass die clr-Transformation ein isomorphismus ist, d.h. die Operationen auf dem Simplex werden auf die entsprechenden Operationen im reellen Raum abgebildet. (b) und (c) kennzeichnen 
eine Isometry (TODO: Quelle Mathebuch), d.h. die Metrik und das Skalarprodukt des Simplex bleiben auch noch der Transformation erhalten.

Based on the fundamental principles in section \autoref{def:principles} and the properties of the Aitchison geometry, it is evident that this generating system represents a compositional link to the 
canonical basis. Furthermore the coefficients in formular 1.1 correspond to the coefficients of the clr transformation as it was first defined by \citet{Aitchison1982}. 
\begin{definition}[clr-transformation]
$\boldsymbol{\rho}=\operatorname{clr}(\boldsymbol{\pi})=\left(\log \left(\pi_{1}\right)-\frac{1}{N} \sum_{k=1}^{N} \log \left(\pi_{k}\right), \ldots, \log \left(\pi_{N}\right)-\frac{1}{N} \sum_{k=1}^{N} \log \left(\pi_{k}\right)\right)$
\end{definition}

The clr coefficients offer several advantages. In particular, for a composition $\mathbf{x_{j}} \in S^{D}$, the clr-transformation establishes a unique relationship between the operations on the simplex (cf. Section \autoref{def:operations})  and the operations in real space. \\

For real constants $\alpha, \beta$ and all $j=1,2$:

\begin{enumerate}[label=(\alph*)]
 \item $\operatorname{clr}\left(\alpha \odot \mathbf{x}_{1} \oplus \beta \odot \mathbf{x}_{2}\right)=\alpha \cdot \operatorname{clr}\left(\mathbf{x}_{1}\right)+\beta \cdot \operatorname{clr}\left(\mathbf{x}_{2}\right)$;  
 \item $\left\langle\mathbf{x}_{1}, \mathbf{x}_{2}\right\rangle_{a}=\left\langle\operatorname{clr}\left(\mathbf{x}_{1}\right), \operatorname{clr}\left(\mathbf{x}_{2}\right)\right\rangle ;$  
 \item $\left\|\mathbf{x}_{1}\right\|_{a}=\left\|\operatorname{clr}\left(\mathbf{x}_{1}\right)\right\|, \quad \mathrm{d}_{a}\left(\mathbf{x}_{1}, \mathbf{x}_{2}\right)=\mathrm{d}\left(\operatorname{clr}\left(\mathbf{x}_{1}\right), \operatorname{clr}\left(\mathbf{x}_{2}\right)\right)$.
\end{enumerate}

Property (a) indicates that the clr-transformation is an isomorphism, meaning that operations on the simplex are mapped to corresponding operations in real space. Properties (b) and (c) characterize an isometry, implying that the metric and inner product of the simplex are preserved under the transformation \citep[p.~35]{PawlowskyGlahn2015a}.


TODO: pi or x? -> für theoretische Aussagen, können wir pi verwenden


Allerdings ist an dieser Stelle wichtig zu bemerken, dass die clr Koefficienten keine Koordinaten in Bezug auf eine Basis des Simplex sind. Außerdem haben sie ähnlich wie die ursprünglichen 
Kompositionsteile eine Beschränkung. Für die clr transformierten Kompositionsteile gilt, dass sie sich zu 0 aufsummieren müssen: $\sum_{j=1}^D \operatorname{clr}({x}_j) = 0$.
Dies hat zur Folge, dass die Kovarianz Matrix von $\operatorname{clr}(\boldsymbol{x})$ singulär ist, was insbesondere für multivariate Methoden problematisch sein kann. Außerdem sind clr-transformierte 
Kompositionen nicht subcompositionally coherent, da das geometrische Mittel von der Anzahl der Kompositionsteile abhängt.
Auch wenn die von Aithcison eingeführten clr-Koefficienten einige Vorteile bieten, ist es hilfreich in einem weiteren Schritt die orthonormalen Koordinaten zu definieren.

At this point, it is important to note that the clr coefficients are not coordinates with respect to a basis of the simplex. Furthermore, similar to the ot the original 
compositional parts, they are subject to a constrain, since $\sum_{j=1}^D \operatorname{clr}({x}_j) = 0$. \\
This implies that the covariance matrix of $\operatorname{clr}(\boldsymbol{x})$ is singular \citep[p.~46]{book}, which can be problematic for multivariate methods. Furthermore, clr-transformed compositions 
are not subcompositionally coherent, since the geometric mean of the number of compositional parts depends on the number of compositional parts. \\
As the clr coefficients introduced by Aitchison offer several advantages, it is helpful to define orthonormal coordinates in a further step.

## Orthonormal coordinates or Coordinate Representations (Cp. Filzmoser et al. 2019, p. 43ff, Egozcue 2003)

Auch wenn die clr-Transformation im Sinne von Aitchison einige Verbesserungen mit sich bringt, so leidet sie doch auch unter einigen Nachteilen, zum 
Beispiel, dass es sich bei clr-transformierten Koordinaten nicht um orthonormale Koordinaten handelt. Zwar bietet die clr-Transformation die Möglichkeit, 
Koordinaten auf dem Simplex in den reelen Raum zu übersetzen, sie unterliegen jedoch nach wie vor der Beschränkung $\sum_{j=1}^D \operatorname{clr}(\boldsymbol{x}_j) = 0$.
Allerdings lässt sich eine orthonormale Basis des Simplex relativ einfach mit Hilfe der Gram-Schmidt Prozedere konstruieren (Egozcue 2003). Damit lassen sich 
unendlich viele orthonormale Basen konstruieren. Um ihre allgemeinen Eigenschaften zu untersuchen, müssen wir zunächst folgende orthonormale Basis definieren:

**Definition 9: contrast matrix**
TODO: transform this definition into the format of Grevens paper
Let $\left\{\mathbf{e}_{1}, \mathbf{e}_{2}, \ldots, \mathbf{e}_{D-1}\right\}$ be an orthonormal basis of the simplex $\mathcal{S}^{D}$ and consider the 
$(D-1, D)$-matrix $\boldsymbol{\Psi}=\left[\psi_{i j}\right]$ in which rows are the 
$\boldsymbol{\Psi}_{i}=\operatorname{clr}\left(\mathbf{e}_{i}\right), i=1,2, \ldots$, $D-1$. This matrix is called contrast matrix associated with the 
orthonormal basis $\left\{\mathbf{e}_{1}, \mathbf{e}_{2}, \ldots, \mathbf{e}_{D-1}\right\}$. Each row is called a (log)contrast (Pawloswky-Glahn et al. 2015, p. 36).

Für eine orthonormale Basis gilt, dass das Aitchison inner product zweier Basiskomponenten dem Kronecker-Delta entspricht. Aufgrund der in Kapitel [...] 
aufgeführten Eigenschaften der clr-Transformation, ist auch klar, dass sich dieser Zusammenhang auf das standard Skalarprodukt der clr-transformierten 
Vektoren überträgt:
$$
\left\langle\mathbf{e}_{j}, \mathbf{e}_{k}\right\rangle_{a}=\left\langle\operatorname{clr}\left(\mathbf{e}_{j}\right), \operatorname{clr}\left(\mathbf{e}_{k}\right)\right\rangle=\delta_{j k}
$$.
Da die Reihen der Matrix $\boldsymbol{\Psi}$ clr Koeffizienten sind, gilt, dass $\sum_{j=1}^D \operatorname{clr}\left(\mathbf{e}_{j}\right) = 0$ für alle $j=1,2, \ldots, D-1$.

Mit dieser Wahl einer orthonormalen Basis lässt sich jede Komposition $\mathbf{x} \in S^{D}$ wie folgt darstellen: 
$$
\mathbf{x}=\bigoplus_{i=1}^{D-1} x_{i}^{*} \odot \mathbf{e}_{i}, \quad x_{i}^{*}=\left\langle\mathbf{x}, \mathbf{e}_{i}\right\rangle_{a} \tag{X}
$$
wobei $\boldsymbol{x}^*$ der Vektor der Koordinaten in Bezug auf die ausgewählte Basis ist.

Wir können nun die clr-Transformation als eine Abbildung $\operatorname{clr}: \mathcal{S}^{D} \rightarrow \mathbb{R}^{D-1}$ definieren, 
die jeder Komposition $\mathbf{x} \in \mathcal{S}^{D}$ die Koordinaten in Bezug auf die orthonormale Basis $\left\{\mathbf{e}_{1}, \mathbf{e}_{2}, \ldots, \mathbf{e}_{D-1}\right\}$ zuordnet.


In diesem Sinne lässt sich die ilr-Transformation wie folgt definieren:
TODO: muss noch


Property 4.5 Consider $\mathbf{x}_{k} \in \mathcal{S}^{D}, k=1,2$, and real constants $\alpha, \beta$; then  

(a) $\operatorname{ilr}\left(\alpha \odot \mathbf{x}_{1} \oplus \beta \odot \mathbf{x}_{2}\right)=\alpha \cdot \operatorname{ilr}\left(\mathbf{x}_{1}\right)+\beta \cdot \operatorname{ilr}\left(\mathbf{x}_{2}\right)=\alpha \cdot \mathbf{x}_{1}^{*}+\beta \cdot \mathbf{x}_{2}^{*}$;

(b) $\left\langle\mathbf{x}_{1}, \mathbf{x}_{2}\right\rangle_{a}=\left\langle\operatorname{ilr}\left(\mathbf{x}_{1}\right), \operatorname{ilr}\left(\mathbf{x}_{2}\right)\right\rangle=\left\langle\mathbf{x}_{1}^{*}, \mathbf{x}_{2}^{*}\right\rangle$;

(c) $\left\|\mathbf{x}_{1}\right\|_{a}=\left\|\operatorname{ilr}\left(\mathbf{x}_{1}\right)\right\|=\left\|\mathbf{x}_{1}^{*}\right\|$;

(d) $\mathrm{d}_{a}\left(\mathbf{x}_{1}, \mathbf{x}_{2}\right)=\mathrm{d}\left(\operatorname{ilr}\left(\mathbf{x}_{1}\right), \operatorname{ilr}\left(\mathbf{x}_{2}\right)\right)=\mathrm{d}\left(\mathbf{x}_{1}^{*}, \mathbf{x}_{2}^{*}\right)$. 

Kurzgesagt, die ilr-Transformation $\operatorname{ilr}: S^{D} \rightarrow \mathbb{R}^{D-1}$ ist eine isometrische Abbildung zwischen Vektorräumen, die die Aitchison Geometrie auf den reelen Raum abbildet. In diesem 
Sinne gleicht sie der clr-Transformation, unterscheidet sich jedoch in der Zahl der Dimensionen.
Mit Hilfe der Matrix $\boldsymbol{\Psi}$ lässt sich außerdem eine direkte Beziehung zwischen den ilr-Koordinaten in $\boldsymbol{x}^*$ und 
den clr-Koefficenten aus der clr-Transformation ableiten:
$$
\mathbf{x}^{*}=\operatorname{ilr}(\mathbf{x})=\operatorname{clr}(\mathbf{x}) \cdot \boldsymbol{\Psi}^{\top}=\ln (\mathbf{x}) \cdot \boldsymbol{\Psi}^{\top}, \tag{X}
$$

An dieser Stelle ist noch zu erwähnen, dass auch Hauptkomponenten orthogonale Basen sind, die nach dem Prinzip ausgerichtet sind die Richtung der maximalen Variablilität wiederzugeben (Pawlowsky-Glahn et al. 2015, p. 38).

TODO: Vorsicht bei der Rücktransformation: Contrast Matrix hat keine Inverse!
TODO: Helmert Matrix was used by Egozcue 2003
TODO: the ilr-transformation induces the *Aitchison measure* on the simplex, which is analogous to the lebesgue measure (Boogart et al. 2013, p. 43)

## Balances

Balances bauen auf einer weiteren spezifische Form von orthonormalen Basen auf, die das vorrangige Ziel haben strukturelle Zusammenhänge der Kompositionsteile zu erfassen und damit eine direkte Interpretation 
ihrer zugehörigen Koordinaten bzw. den *Balances* ermöglichen. Die Basisvektoren werden in diesem Fall *balancing elements* genannt und können theoretisch und empirisch 
fundierte Zusammenhänge der Kompositionsteile untereinander repräsentieren. 

Als letztes relevantes Prinzip zur Einführung mit der Arbeit an Kompositionsdaten, soll an dieser Stelle noch das *Prinzip der Arbeit in Koordinaten* erwähnt werden. Wie bereits 
ersichtlich wird von Koordinaten in Zusammenhang mit einem System orthonormalen Basen gesprochen. In diesem Sinne wird im Zusammenhang mit der clr-Transformation von **clr-Koefficienten** 
und bei der ilr-Transformation, die auf der Anwendung von orthonormalen Basen beruht, von ilr-Koordinaten gesprochen.
Die Grundidee hinter dem Prinzip ist, dass Koordinaten mit einer orthonormalen Basis bestimmten standardisierten Operationsregeln gehorchen. Dazu gehören insbesondere die geteilten 
Eigenschaften von Perturbation und Addition bzw. von Powering und Multiplikation: 
$$
\operatorname{ilr}(\mathbf{x} \oplus \mathbf{y})=\operatorname{ilr}(\mathbf{x})+i \operatorname{lr}(\mathbf{y})=\mathbf{x}^{*}+\mathbf{y}^{*}, \quad \operatorname{ilr}(\alpha \odot \mathbf{x})=\alpha \cdot \operatorname{ilr}(\mathbf{x})=\alpha \cdot \mathbf{x}^{*} \tag{X}
$$

Allgemein lässt sich formulieren, dass bei der Analyse von Kompositionsdaten Ergebnisse, die mit den ursprünglichen Kompositionen und der Aitchison Geomtry und Ergebnisse, die auf 
den ilr-Koordinaten unter der Nutzen der normalen euklidischen Geometry beruhen, identisch sind. Dies resultiert in einer "Dualität" der Representation von Kompositionsdaten, die 
sowohl auf dem Simplex als auch in ihren Koordinaten dargestellt und analysiert werden können (Pawlowsky-Glahn et al. 2015, p.43).

In der Regel ist der Simplex geeignet um die Daten im Kontext der real beobachteten Kompositionen zu interpretieren, während (ilr) Koordinaten mit einer beliebigen orthonormalen Basis 
insbesondere für die Anwendung multivariater Methoden geeignet sind.
In weiteren Verlauf dieser Arbeit werden beide Varianten ausgiebig genutzt.

Balances are built upon another specific form of orthonormal bases, whose primary goal is to capture the structural relationships among the components of a composition, thereby enabling 
a direct interpretation of their associated coordinates. In this case, the basis vectors are called \emph{balancing elements} and can represent theoretically and empirically founded relationships 
between the compositional parts. The coordinates that result from the application of such a basis are called \emph{balances} \citet[~p.38]{Pawlowsky-Glahn2015a}.

As the last relevant principle for introducing work with compositional data, the principle of working in coordinates should be mentioned here. As already evident, we speak of coordinates 
in connection with a system of orthonormal bases. In this sense, in the context of the clr-transformation, we refer to clr-coefficients, and in the ilr-transformation, which is based on the application of orthonormal bases, we speak of ilr-coordinates.

The fundamental idea behind this principle is that coordinates associated with an orthonormal basis obey certain standardized operational rules. These include, in particular, the shared properties of perturbation and addition, as well as powering and multiplication:

$$ \operatorname{ilr}(\mathbf{x} \oplus \mathbf{y}) = \operatorname{ilr}(\mathbf{x}) + \operatorname{ilr}(\mathbf{y}) = \mathbf{x}^{} + \mathbf{y}^{}, \quad \operatorname{ilr}(\alpha \odot \mathbf{x}) = \alpha \cdot \operatorname{ilr}(\mathbf{x}) = \alpha \cdot \mathbf{x}^{*} \tag{X} $$

In general, it can be stated that in the analysis of compositional data, results obtained with the original compositions using Aitchison geometry and results based on ilr-coordinates using standard Euclidean geometry are identical. This results in a "duality" in the representation of compositional data, which can be presented and analyzed both on the simplex and in their coordinate form (Pawlowsky-Glahn et al. 2015, p.43).

Typically, the simplex is suitable for interpreting the data in the context of the real observed compositions, while (ilr) coordinates with an arbitrary orthonormal basis are particularly suitable for the application of multivariate methods.

In the further course of this work, both variants will be used extensively.

## Normality on the simplex

## Zeros

Anhand der Definition einer D-part composition wird bereits deutlich, dass Kompositionsteile strikt positiv sein müssen. In tatsächlichen Beobachtungen von Kompositionen ist aber durchaus möglich 
und je nach Kontext auch nicht ungewöhnlich, dass Nullwerte für einzelne Kompositionsteile beobachtet werden.

## Descriptive statistics 

TODO: geomatrisches Mean für Komposition und für Datensatz sind nicht identisch!

Es wurde bereits herausgearbeitet, dass die üblichen Methoden einer auf absoluten Werten basierenden statistischen Analyse für Kompositionsdaten 
nicht geeignet sind. Im Besonderen gilt dies auch für die typischen deskriptiven Schätzer, wie dem arithmetrischen Durchschnitt und der Varianz, 
die nicht mit der Aitchison Geometry vereinbar sind (Vgl. Pawlowsky-Glahn, p. 66ff). 

Stattdessen sollten Methoden für die Einschätzung von Lokalität und Variabilität (Spread) der Daten verwendet werden, die im Einklang mit den Grundlagen der 
Kompositionsdatenanalyse stehen. Diese werden 
im Folgenden aufgeführt und im kapitel [...] am praktischen Datensatz umgesetzt. The observed data matrix $\boldsymbol{x_i} = (x_{i 1}, \ldots, x_{i D})$ with $i = 1, \ldots, n$ contains *n* rows of observed 
compositions with *D* columns for the compositional parts. 

Standardmethoden der beschreibenden multivariaten statistischen Analyse beinhalten in der Regel measures of central tendency and dispersion, i.e. the 
arithmetric mean and the variance of the multivariate data (Vgl. Pawlowsky-Glahn et al. 2015, p. 66). Im Kontext der Aitchison Geometry werden diese 
durch *center* (Aitchison, 1997), *variation matrix* and *total variance* (Aitchison, 1986) ersetzt.

**Definition 9: Sample center**
The closed geometric mean is a measure for the central tendancy of a compositional sample. It is called *center*.  For the observed data matrix $\boldsymbol{x}$ 
it is defined as: $\operatorname{cen}(\mathbf{x})=\hat{\mathbf{g}}=\mathcal{C}\left[\hat{g}_{1}, \hat{g}_{2}, \ldots, \hat{g}_{D}\right]$
with $\hat{g}_{j}=\left(\prod_{i=1}^{n} x_{i j}\right)^{1 / n}, j=1,2, \ldots, D$.

This corresponds to: 
$$
\begin{equation*}
\overline{\mathbf{x}}=\frac{1}{N} \odot \bigoplus_{n=1}^{N} \mathbf{x}_{n}=\operatorname{clr}^{-1}\left(\frac{1}{N} \sum_{n=1}^{N} \operatorname{clr}\left(\mathbf{x}_{n}\right)\right)=\mathscr{C}\left[\exp \left(\frac{1}{N} \sum_{n=1}^{N} \ln \left(\mathbf{x}_{n}\right)\right)\right] \tag{4.1}
\end{equation*}
$$
With $\mathscr{C}$ being the closure operation.

TODO: How to compute that

**Definition 10: Variation matrix**
The *variation matrix* is a measure for dispersion in a compositional sample. It is defined as: 
$$
\mathbf{T}=\left(\begin{array}{cccc}
t_{11} & t_{12} & \ldots & t_{1 D} \\
t_{21} & t_{22} & \ldots & t_{2 D} \\
\vdots & \vdots & \ddots & \vdots \\
t_{D 1} & t_{D 2} & \ldots & t_{D D}
\end{array}\right), \quad t_{i j}=\operatorname{var}\left(\ln \frac{x_{i}}{x_{j}}\right)
$$
TODO: add normalized version? -> if so introduce **balances** here as well

**Definition 11: Sample total variance**
The *Sample total variance* is a measure for global dispersion in a compositional sample. It is defined as: 
$$
\operatorname{totvar}[\mathbf{x}]=\frac{1}{2 D} \sum_{i, j=1}^{D} \operatorname{var}\left(\ln \frac{x_{i}}{x_{j}}\right)=\frac{1}{2 D} \sum_{i, j=1}^{D} t_{i j}=\frac{1}{n} \sum_{k=1}^{n} \mathrm{~d}_{a}^{2}\left(\mathbf{x}_{k}, \hat{\mathbf{g}}\right)
$$
TODO: change index i to k or l

Since any constant cancels out when taking ratios the measures of dispersion do not depend on any closure, i.e. the scale of the observerd data.

## Multivariate techniques 


## Sonstiges

Interpretation des Konvergenzkriteriums: eps = 0.01 bedeutet, dass es pro Komponente im Durchschnitt nur noch eine Abweichung von 1% gibt. 
Bei der Kovarianmatrix beträgt die durchschnittliche Abweichung epsilon/d. D.h. bei kleineren Dimensionalitäten sollte epsilon kleiner 
gewählt werden. 


